name: CI Pipeline 
 
on: 
  push: 
    branches: [ main, master ] 
  pull_request: 
    branches: [ main, master ] 
  workflow_dispatch: 
 
jobs: 
  build: 
    runs-on: ubuntu-latest 
 
    steps: 
    - name: Checkout code 
      uses: actions/checkout@v4 
 
    - name: Setup Node.js 
      uses: actions/setup-node@v4 
      with: 
        node-version: '18' 
 
    - name: Create package.json with test script 
      run: | 
        echo '{ 
          "name": "node-hello", 
          "version": "1.0.0", 
          "scripts": { 
            "test": "echo \"Tests passed!\" ^&^& exit 0" 
          } 
        }' > package.json 
 
    - name: Install dependencies 
      run: npm install 
 
    - name: Run tests 
      run: npm test 
 
    - name: Build completed 
      run: echo "?? Pipeline completed successfully!" 
